name: Firebase Hosting Deploy

on:
  push:
    branches:
      - master  # Ou qualquer outra branch que você deseja que dispare o deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Firebase CLI
        uses: wzieba/Firebase-Action@v2
        with:
          firebase_token: ${{ secrets.FIREBASE_AUTH_TOKEN }}

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_AUTH_TOKEN }}
